# Generated by Django 5.0.7 on 2024-08-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='available_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Конференція'), ('seminar', 'Семінар'), ('workshop', 'Воркшоп')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='electronic_ticket',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
