# Generated by Django 5.0.7 on 2024-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Конференція'), ('seminar', 'Семінар'), ('workshop', 'Воркшоп')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
