# Generated by Django 5.0.7 on 2024-08-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_ticket_event_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
