# Generated by Django 5.0.7 on 2024-08-08 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type_alter_program_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='event',
        ),
        migrations.AddField(
            model_name='program',
            name='available_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='program',
            name='total_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.program'),
            preserve_default=False,
        ),
    ]
