# Generated by Django 5.0.7 on 2024-08-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_ticket_event_program_available_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='electronic_ticket',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
