version: '3'

services:
  django_front_app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/django_app/registration_platform_front
    ports:
      - "8001:8001"
    depends_on:
#      - backend_app
      - redis
      - psql_db
    networks:
      - app_network

  psql_db:
    image: postgres
    environment:
      POSTGRES_DB: registration_platform_front_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - app_network

  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - app_network

#  backend_app:
#    image: registration_platform_back-django_app
#    environment:
#      DB_NAME: registration_platform_back_psql_db-1
#      DB_USER: admin
#      DB_PASSWORD: admin
#      DB_HOST: psql_db
#      DB_PORT: 5432
#    ports:
#      - "8002:8000"
#    depends_on:
#      - redis
#    networks:
#      - app_network

networks:
  app_network:
    driver: bridge
