version: '3'

services:
  django_app:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django_app/registration_platform_back
    ports:
      - "8000:8000"
    depends_on:
      - psql_db

  psql_db:
    image: postgres
    environment:
      POSTGRES_DB: registration_platform_back_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

#  celety-beat:
#    build: .
#    command: celery -A registration_platform_back_db beat -l info
#    volumes:
#      - ./registration_platform_back_db:/django_app/registration_platform_back_db
#    depends_on:
#      - redis
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0

#  celery-worker:
#    build: .
#    command: celery -A registration_platform_back_db worker -l info
#    volumes:
#      - ./registration_platform_back_db:/django_app/registration_platform_back_db
#    depends_on:
#      - redis
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0